"""Fix errors prompt — fixes compilation or validation errors in CUDA kernel."""

from nodes._llm_helper import format_strategy


def build(ctx: dict) -> tuple[str, str]:
    system = """# Fix Kernel Errors

You are debugging a CUDA kernel. Your goal is to fix the error while maintaining **maximum performance**. Do not throw away the optimization strategy unless the error proves that strategy is invalid.

The kernel either failed to compile or produced incorrect results.

## Input

You will receive:
1. The current kernel implementation (kernel.cu)
2. The error message or validation failure details
3. The reference kernel for comparison (ref_kernel.cu)

## Task

Fix the kernel(s) to resolve the error. Preserve the intended optimization approach when possible (one or more kernels — keep the pipeline shape unless the error proves it invalid), make the smallest targeted changes that restore correctness, and output the corrected kernel code.

Errors may be: a **host-compile** failure of the generated driver (marked `[COMPILE ERROR]`) — usually a kernel signature/symbol mismatch you should fix here (pure C++ region errors are regenerated by the config step); an **NVRTC** kernel compile error; or a **validation** mismatch. Fix the kernel-side cause.

If the failure is caused by parameter assumptions, launch geometry, tiling, or shared-memory sizing, update the kernel so it is consistent with those assumptions rather than silently changing the algorithm.

## Common Error Types

### Compilation Errors

**Undefined parameter:**
```
error: 'TILE_SIZE' was not declared in this scope
```
Fix: Ensure the parameter is declared in the CACAO:PARAMS region (AddParameter) and spelled the same in the kernel.

**Shared memory size:**
```
error: expression must have a constant value
```
Fix: Shared memory sizes must be compile-time constants (use parameters, not variables).

**Type mismatch:**
```
error: no matching function for call to 'make_float4'
```
Fix: Check argument types match the function signature.

**Cooperative groups / grid sync:**
```
catastrophic error: cannot open source file "cooperative_groups.h"
# or: identifier "grid_group" / "this_grid" is undefined
# or: silent runtime failure with grid-wide sync
```
Fix: Remove `#include <cooperative_groups.h>` and any `grid.sync()` / cooperative-grid calls. KTT uses standard `cudaLaunchKernel`, so grid-wide coordination is unavailable. Restrict synchronization to a single block (`__syncthreads`), or use atomic counters in global memory for cross-block handoff.

### Validation Errors

**Output mismatch:**
```
Validation failed: max diff = 0.5, tolerance = 0.001
```
Possible causes:
- Algorithm bug (wrong indexing, wrong loop bounds)
- Race condition (missing __syncthreads)
- Precision issue (accumulation order)

**Out of bounds / illegal address:**
```
CUDA error: an illegal memory access was encountered
CUDA_ERROR_ILLEGAL_ADDRESS in function cuEventCreate
```
Two common causes:
1. **Out-of-bounds array access** — add bounds checking (`if (i < N)`).
2. **`extern __shared__` with no size** — the tuner always launches with 0 bytes of dynamic shared memory. Fix: replace `extern __shared__ float smem[]` with a static declaration: `__shared__ float smem[COMPILE_TIME_SIZE]`.

Treat illegal memory access as a top-priority correctness failure. A single out-of-bounds write can invalidate the whole tuning iteration.

### Runtime Errors

**Launch failure:**
```
CUDA error: too many resources requested for launch
```
Fix: Reduce shared memory or register usage, or use smaller block size.

## Output Format

Output ONLY the corrected CUDA kernel code. No markdown, no explanation.

## Critical Repair Rules

1. **No illegal memory accesses** — every global and shared-memory read/write must be provably in-bounds.
2. **Keep parameter usage consistent** — use only parameter names declared in the CACAO:PARAMS region (AddParameter), and preserve relationships implied by launch geometry and constraints.
3. **Use static shared memory only** — never introduce `extern __shared__`.
4. **Preserve single-kernel structure and interface** — keep `extern "C"`, kernel name, and function signature (vector pointer arguments only; scalars are compiler defines). Do not add scalar parameters to the function signature.
5. **Prefer targeted fixes over rewrites** — only restructure aggressively if the current design cannot be repaired safely.

## Debugging Checklist

1. **Indexing**: Are row/col calculations correct?
2. **Sync points**: Is `__syncthreads()` used after shared memory writes?
3. **Bounds**: Does the kernel handle non-divisible dimensions?
4. **Memory layout**: Does access pattern match reference (row-major vs col-major)?
5. **Accumulation**: Is the result accumulated correctly?
6. **Parameter usage**: Are all parameters used as intended?
7. **Launch assumptions**: Do block/tile/work mappings still match the tuning constraints?
8. **Memory safety**: Can any thread write outside the valid output or shared-memory region for any tested configuration?
"""

    parts = []
    if ctx.get("problem_yaml"):
        parts.append(f"## Problem Definition:\n```yaml\n{ctx['problem_yaml']}\n```")
    if ctx.get("ref_kernel"):
        parts.append(f"## Reference Kernel:\n```cuda\n{ctx['ref_kernel']}\n```")
    if ctx.get("plan"):
        parts.append(f"## Optimization Plan:\n{ctx['plan']}")
    strategy_text = format_strategy(ctx.get("strategy"))
    if strategy_text:
        parts.append(strategy_text)
    if ctx.get("parent_context"):
        parts.append(ctx["parent_context"])
    if ctx.get("iteration_history"):
        parts.append(ctx["iteration_history"])
    if ctx.get("current_context"):
        parts.append(
            ctx["current_context"]
            + "\n\n→ The feedback above is the **authoritative instruction** for what "
            "must change. If it conflicts with the proposal or iteration history, "
            "follow the feedback. Use it together with the tuner output and the "
            "current kernel to produce the smallest correct fix."
        )
    if ctx.get("user_messages"):
        parts.append(ctx["user_messages"])
    parts.append(
        "Fix the kernel errors. Output ONLY the corrected kernel code, no markdown.\n\n"
        "CRITICAL REMINDERS — verify before writing code:\n"
        "1. NO `extern __shared__` — use ONLY static: `__shared__ float arr[COMPILE_TIME_SIZE]`. "
        "Dynamic shared memory crashes every config.\n"
        "2. NO host headers — `#include <stdint.h>`, `<cuda.h>`, `<cuda_runtime.h>`, `<stdio.h>` "
        "are forbidden. Use built-in types.\n"
        "3. Function signature: vector pointers ONLY. Scalars (M, N, K, etc.) are `#define` "
        "constants, NOT function parameters.\n"
        '4. `extern "C"` required on the kernel.\n'
        "5. Every global and shared memory access must be provably in-bounds."
    )

    return system, "\n\n".join(parts)
