"""Fix errors prompt — fixes compilation or validation errors in CUDA kernel."""

from nodes._llm_helper import format_strategy
from prompts._system_overview import SYSTEM_OVERVIEW, NVRTC_RULES
from prompts._tensor_core_reference import TENSOR_CORE_REFERENCE


def build(ctx: dict) -> tuple[str, str]:
    system = (
        """# Fix Kernel Errors

You are debugging a CUDA kernel. Your goal is to fix the error while maintaining **maximum performance**. Do not throw away the optimization strategy unless the error proves that strategy is invalid.

The kernel either failed to compile or produced incorrect results.

"""
        + SYSTEM_OVERVIEW
        + """
## Input

You will receive:
1. The current kernel implementation (kernels.cu)
2. The error message or validation failure details
3. The reference kernel for comparison (ref_kernel.cu)

## Task

Fix the kernel(s) to resolve the error. Preserve the intended optimization approach when possible (one or more kernels — keep the pipeline shape unless the error proves it invalid), make the smallest targeted changes that restore correctness, and output the corrected kernel code.

Errors may be: a **host-compile** failure of the generated driver (marked `[COMPILE ERROR]`) — usually a kernel signature/symbol mismatch you should fix here (pure C++ region errors are regenerated by the config step); an **NVRTC** kernel compile error; or a **validation** mismatch. Fix the kernel-side cause.

If the failure is caused by parameter assumptions, launch geometry, tiling, or shared-memory sizing, update the kernel so it is consistent with those assumptions rather than silently changing the algorithm.

## Common Error Types

### Compilation Errors

**Undefined parameter:**
```
error: 'TILE_SIZE' was not declared in this scope
```
Fix: Ensure the parameter is declared in the CACAO:PARAMS region (AddParameter) and spelled the same in the kernel.

**Shared memory size:**
```
error: expression must have a constant value
```
Fix: Shared memory sizes must be compile-time constants (use parameters, not variables).

**Type mismatch:**
```
error: no matching function for call to 'make_float4'
```
Fix: Check argument types match the function signature.

**Unsupported wmma shape:**
```
error: incomplete type is not allowed
```
On a `wmma::fragment<>` declaration this means the (M,N,K)/dtype combo is not specialized — see the tensor-core table below.

### Validation Errors

**Output mismatch:**
```
Validation failed: max diff = 0.5, tolerance = 0.001
```
Possible causes:
- Algorithm bug (wrong indexing, wrong loop bounds)
- Race condition (missing __syncthreads)
- Precision issue (accumulation order)

**Out of bounds / illegal address:**
```
CUDA error: an illegal memory access was encountered
CUDA_ERROR_ILLEGAL_ADDRESS in function cuEventCreate
```
Two common causes:
1. **Out-of-bounds array access** — add bounds checking (`if (i < N)`).
2. **`extern __shared__` without a binding** — the launch gets 0 dynamic bytes unless the configure step registered an `AddArgumentLocal` argument for this kernel. Fix: replace with a static declaration `__shared__ float smem[COMPILE_TIME_SIZE]` (or note that configure must add the binding).

Treat illegal memory access as a top-priority correctness failure. A single out-of-bounds write can invalidate the whole tuning iteration.

### Runtime Errors

**Launch failure:**
```
CUDA error: too many resources requested for launch
```
Fix: Reduce shared memory or register usage, or use smaller block size.

**Grid-wide sync (cooperative groups):**
```
unspecified launch failure   # at runtime — the kernel COMPILED fine
```
`cg::this_grid().sync()` compiles under NVRTC but KTT launches with plain `cuLaunchKernel`, so grid sync fails at runtime. Block/warp-scope cooperative groups (`cg::tiled_partition<32>`, `cg::reduce`) are fine. Fix: keep synchronization inside a block (`__syncthreads`), use atomic counters in global memory, or split into pipeline stages (each kernel launch is a grid-wide barrier).

## Output Format

Output ONLY the corrected CUDA kernel code. No markdown, no explanation.

## Critical Repair Rules

1. **No illegal memory accesses** — every global and shared-memory read/write must be provably in-bounds.
2. **Keep parameter usage consistent** — use only parameter names declared in the CACAO:PARAMS region (AddParameter), and preserve relationships implied by launch geometry and constraints.
3. **Preserve structure where the error allows** — keep `extern "C"` on every `__global__` and the kernel names/pipeline shape unless the error proves them invalid. Signatures MAY change when the fix requires it (runtime scalar args are legal parameters): the configure step re-binds arguments after this fix — but avoid gratuitous signature churn.
4. **Prefer targeted fixes over rewrites** — only restructure aggressively if the current design cannot be repaired safely.

## Debugging Checklist

1. **Indexing**: Are row/col calculations correct?
2. **Sync points**: Is `__syncthreads()` used after shared memory writes?
3. **Bounds**: Does the kernel handle non-divisible dimensions?
4. **Memory layout**: Does access pattern match reference (row-major vs col-major)?
5. **Accumulation**: Is the result accumulated correctly?
6. **Parameter usage**: Are all parameters used as intended?
7. **Launch assumptions**: Do block/tile/work mappings still match the tuning constraints?
8. **Memory safety**: Can any thread write outside the valid output or shared-memory region for any tested configuration?

"""
        + NVRTC_RULES
        + TENSOR_CORE_REFERENCE
    )

    parts = []
    if ctx.get("problem_yaml"):
        parts.append(f"## Problem Definition:\n```yaml\n{ctx['problem_yaml']}\n```")
    if ctx.get("ref_kernel"):
        # ref_language: the reference may be CUDA, C, or Python — fencing a Python
        # reference as ```cuda misleads the model about what it is reading.
        parts.append(
            f"## Reference Kernel:\n```{ctx.get('ref_language', 'cuda')}\n{ctx['ref_kernel']}\n```"
        )
    # The boundary and the scalar contract: a retry is often fixing exactly this — an
    # undefined identifier because a scalar was used as a macro when it is a runtime
    # argument. Without them the fix is a guess.
    if ctx.get("inputs_hpp"):
        parts.append(
            "## Inputs (inputs.hpp) — your kernel's I/O boundary.\n"
            "**Compiled into the host driver, NOT into your kernel.** NVRTC compiles "
            "kernels.cu on its own, so nothing here — including every `inline constexpr` "
            "— is visible to a kernel unless it is a `-D` macro or an argument.\n"
            f"```cpp\n{ctx['inputs_hpp']}\n```"
        )
    if ctx.get("scalar_contract"):
        parts.append(ctx["scalar_contract"])
    if ctx.get("plan"):
        parts.append(f"## Optimization Plan:\n{ctx['plan']}")
    strategy_text = format_strategy(ctx.get("strategy"))
    if strategy_text:
        parts.append(strategy_text)
    if ctx.get("parent_context"):
        parts.append(ctx["parent_context"])
    if ctx.get("iteration_history"):
        parts.append(ctx["iteration_history"])
    if ctx.get("current_context"):
        parts.append(
            ctx["current_context"]
            + "\n\n→ The feedback above is the **authoritative instruction** for what "
            "must change. If it conflicts with the proposal or iteration history, "
            "follow the feedback. Use it together with the tuner output and the "
            "current kernel to produce the smallest correct fix."
        )
    if ctx.get("user_messages"):
        parts.append(ctx["user_messages"])
    parts.append(
        "Fix the kernel errors. Output ONLY the corrected kernel code, no markdown.\n\n"
        "CRITICAL REMINDERS — verify before writing code:\n"
        "1. Static `__shared__ arr[MACRO_SIZE]` unless configure binds AddArgumentLocal.\n"
        "2. No glibc-reaching headers (`<stdint.h>`, `<cstdint>`, `<cuda.h>`, `<stdio.h>`).\n"
        '3. `extern "C"` on every kernel; no gratuitous signature changes.\n'
        "4. Every global and shared memory access must be provably in-bounds."
    )

    return system, "\n\n".join(parts)
