// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>
#include <cstring>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int N = 1048576;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<float> gen_tableA() {
    std::vector<float> v(20 * 18);
    std::mt19937 rng(1284527009u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_tableB() {
    std::vector<float> v(20 * 18);
    std::mt19937 rng(3583574555u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<int> gen_chains() {
    std::vector<int> v(static_cast<size_t>(N) + 17);
    std::mt19937 rng(1611589309u);
    std::uniform_int_distribution<int> d(0, 19);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_primaryScore() {
    return std::vector<float>(static_cast<size_t>(N), 0.0f);
}
inline std::vector<float> gen_secondaryScore() {
    return std::vector<float>(static_cast<size_t>(N), 0.0f);
}

// --- CPU reference (ref_cpu.c, linked into the driver; scalars are -D flags) --
extern "C" void peptides_reference(const float* tableA, const float* tableB, const int* chains, float* primaryScore, float* secondaryScore);
namespace cacao_ref {
inline const std::vector<float> h_tableA = gen_tableA();
inline const std::vector<float> h_tableB = gen_tableB();
inline const std::vector<int> h_chains = gen_chains();
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId tableA;
    ktt::ArgumentId tableB;
    ktt::ArgumentId chains;
    ktt::ArgumentId primaryScore;
    ktt::ArgumentId secondaryScore;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.tableA = t.AddArgumentVector(cacao_ref::h_tableA, ktt::ArgumentAccessType::ReadOnly);
    in.tableB = t.AddArgumentVector(cacao_ref::h_tableB, ktt::ArgumentAccessType::ReadOnly);
    in.chains = t.AddArgumentVector(cacao_ref::h_chains, ktt::ArgumentAccessType::ReadOnly);
    in.primaryScore = t.AddArgumentVector(gen_primaryScore(), ktt::ArgumentAccessType::WriteOnly);
    in.secondaryScore = t.AddArgumentVector(gen_secondaryScore(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.primaryScore, in.secondaryScore};
    in.boundary  = {in.tableA, in.tableB, in.chains, in.primaryScore, in.secondaryScore};
    in.defines   = "-DN=1048576";

    // CPU reference: one computation per validated buffer (engine skeleton
    // skips SetReferenceKernel when the problem's reference is cpu_c).
    t.SetReferenceComputation(in.primaryScore, [](void* buffer) {
        std::vector<float> s_secondaryScore(static_cast<size_t>(N));
        peptides_reference(cacao_ref::h_tableA.data(), cacao_ref::h_tableB.data(), cacao_ref::h_chains.data(), static_cast<float*>(buffer), s_secondaryScore.data());
    });
    t.SetReferenceComputation(in.secondaryScore, [](void* buffer) {
        std::vector<float> s_primaryScore(static_cast<size_t>(N));
        peptides_reference(cacao_ref::h_tableA.data(), cacao_ref::h_tableB.data(), cacao_ref::h_chains.data(), s_primaryScore.data(), static_cast<float*>(buffer));
    });
    return in;
}
