// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>
#include <cstring>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int STUDENTS = 4096;
inline constexpr int QUESTIONS = 1024;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<int> gen_results() {
    std::vector<int> v(static_cast<size_t>(STUDENTS) * static_cast<size_t>(QUESTIONS));
    std::mt19937 rng(2678318100u);
    std::uniform_int_distribution<int> d(0, 100);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_avg_stud() {
    return std::vector<float>(static_cast<size_t>(STUDENTS), 0.0f);
}
inline std::vector<float> gen_avg_que() {
    return std::vector<float>(static_cast<size_t>(QUESTIONS), 0.0f);
}

// --- CPU reference (ref_cpu.c, linked into the driver; scalars are -D flags) --
extern "C" void averages_reference(const int* results, float* avg_stud, float* avg_que);
namespace cacao_ref {
inline const std::vector<int> h_results = gen_results();
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId results;
    ktt::ArgumentId avg_stud;
    ktt::ArgumentId avg_que;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.results = t.AddArgumentVector(cacao_ref::h_results, ktt::ArgumentAccessType::ReadOnly);
    in.avg_stud = t.AddArgumentVector(gen_avg_stud(), ktt::ArgumentAccessType::WriteOnly);
    in.avg_que = t.AddArgumentVector(gen_avg_que(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.avg_stud, in.avg_que};
    in.boundary  = {in.results, in.avg_stud, in.avg_que};
    in.defines   = " -DSTUDENTS=4096 -DQUESTIONS=1024";

    // CPU reference: one computation per validated buffer (engine skeleton
    // skips SetReferenceKernel when the problem's reference is cpu_c).
    t.SetReferenceComputation(in.avg_stud, [](void* buffer) {
        std::vector<float> s_avg_que(static_cast<size_t>(QUESTIONS));
        averages_reference(cacao_ref::h_results.data(), static_cast<float*>(buffer), s_avg_que.data());
    });
    t.SetReferenceComputation(in.avg_que, [](void* buffer) {
        std::vector<float> s_avg_stud(static_cast<size_t>(STUDENTS));
        averages_reference(cacao_ref::h_results.data(), s_avg_stud.data(), static_cast<float*>(buffer));
    });
    return in;
}
