// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int N = 33554432;
inline constexpr int R = 256;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<float> gen_input() {
    std::vector<float> v(static_cast<size_t>(N));
    std::mt19937 rng(3626513111u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_average() {
    return std::vector<float>(static_cast<size_t>(N), 0.0f);
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId input;
    ktt::ArgumentId average;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.input = t.AddArgumentVector(gen_input(), ktt::ArgumentAccessType::ReadOnly);
    in.average = t.AddArgumentVector(gen_average(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.average};
    in.boundary  = {in.input, in.average};
    in.defines   = " -DN=33554432 -DR=256";
    return in;
}
