// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>
#include <cstdlib>
#include <fstream>
#include <cstring>
#include <stdexcept>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int kSizeM = 2048;
inline constexpr int kSizeN = 2048;
inline constexpr int kSizeK = 2048;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<float> gen_mat_a() {
    std::vector<float> v(static_cast<size_t>(kSizeM) * static_cast<size_t>(kSizeK));
    std::mt19937 rng(1886651486u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_mat_b() {
    std::vector<float> v(static_cast<size_t>(kSizeN) * static_cast<size_t>(kSizeK));
    std::mt19937 rng(3917305316u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_mat_c() {
    return std::vector<float>(static_cast<size_t>(kSizeM) * static_cast<size_t>(kSizeN), 0.0f);
}

// --- Python reference (ref.py, invoked via utils.python_ref_runner) -------------
namespace cacao_ref {
inline const std::vector<float> h_mat_a = gen_mat_a();
inline const std::vector<float> h_mat_b = gen_mat_b();
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId kSizeM_;
    ktt::ArgumentId kSizeN_;
    ktt::ArgumentId kSizeK_;
    ktt::ArgumentId mat_a;
    ktt::ArgumentId mat_b;
    ktt::ArgumentId mat_c;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.kSizeM_ = t.AddArgumentScalar(kSizeM);
    in.kSizeN_ = t.AddArgumentScalar(kSizeN);
    in.kSizeK_ = t.AddArgumentScalar(kSizeK);
    in.mat_a = t.AddArgumentVector(cacao_ref::h_mat_a, ktt::ArgumentAccessType::ReadOnly);
    in.mat_b = t.AddArgumentVector(cacao_ref::h_mat_b, ktt::ArgumentAccessType::ReadOnly);
    in.mat_c = t.AddArgumentVector(gen_mat_c(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.mat_c};
    in.boundary  = {in.kSizeM_, in.kSizeN_, in.kSizeK_, in.mat_a, in.mat_b, in.mat_c};
    in.defines   = "";

    // Python reference: one computation per validated buffer (engine skeleton
    // skips SetReferenceKernel when the problem's reference is python).
    t.SetReferenceComputation(in.mat_c, [](void* buffer) {
        { std::ofstream f("cacao_in_mat_a.bin", std::ios::binary); f.write(reinterpret_cast<const char*>(cacao_ref::h_mat_a.data()), static_cast<std::streamsize>(cacao_ref::h_mat_a.size() * sizeof(float))); }
        { std::ofstream f("cacao_in_mat_b.bin", std::ios::binary); f.write(reinterpret_cast<const char*>(cacao_ref::h_mat_b.data()), static_cast<std::streamsize>(cacao_ref::h_mat_b.size() * sizeof(float))); }
        const int rc = std::system("PYTHONPATH=/home/u550615/CACAO /home/u550615/miniconda3/envs/ktt/bin/python -m utils.python_ref_runner --inputs inputs.yaml --ref ref.py --function gemm_reference --target mat_c --output cacao_ref_mat_c.bin");
        if (rc != 0)
            throw std::runtime_error("python reference failed (exit " + std::to_string(rc) + "): mat_c");
        std::ifstream f("cacao_ref_mat_c.bin", std::ios::binary);
        if (!f)
            throw std::runtime_error("python reference wrote no cacao_ref_mat_c.bin");
        f.read(static_cast<char*>(buffer), static_cast<std::streamsize>(static_cast<size_t>(kSizeM) * static_cast<size_t>(kSizeN) * sizeof(float)));
        if (f.gcount() != static_cast<std::streamsize>(static_cast<size_t>(kSizeM) * static_cast<size_t>(kSizeN) * sizeof(float)))
            throw std::runtime_error("python reference produced a short cacao_ref_mat_c.bin");
    });
    return in;
}
