// framework.cpp — GENERATED by utils/framework.py. Do not edit by hand.
// Engine skeleton (argument-agnostic) + user inputs.hpp + three LLM regions.
#include <iostream>
#include <memory>
#include <string>
#include <vector>

#include <Ktt.h>
#include "inputs.hpp"

int main(int argc, char** argv)
{
    // ---- runtime args (argv) ----
    ktt::PlatformIndex platform = (argc > 1) ? std::stoul(argv[1]) : 0;
    ktt::DeviceIndex   device   = (argc > 2) ? std::stoul(argv[2]) : 0;
    const double       duration  = (argc > 3) ? std::stod(argv[3]) : 20.0;
    const double       tolerance = (argc > 4) ? std::stod(argv[4]) : 1.0;
    const std::string  output     = (argc > 5) ? argv[5] : "results";
    const std::string  kernelFile = (argc > 6) ? argv[6] : "kernels.cu";
    const std::string  refFile    = (argc > 7) ? argv[7] : "ref_kernel.cu";

    // ---- tuner ----
    ktt::Tuner tuner(platform, device, ktt::ComputeApi::CUDA);
    tuner.SetGlobalSizeType(ktt::GlobalSizeType::OpenCL);
    tuner.SetTimeUnit(ktt::TimeUnit::Microseconds);
    tuner.SetCompilerOptions("-I/usr/local/cuda/include");

    const ktt::DimensionVector ndRange(kSizeM, kSizeN);

    // ---- inputs (user-owned; the entire I/O boundary) ----
    Inputs in = DefineInputs(tuner);

    // ---- reference kernel (engine-owned validation) ----
    const ktt::KernelDefinitionId refDef = tuner.AddKernelDefinitionFromFile(
        "gemm_reference", refFile, ndRange, ktt::DimensionVector(8, 8));
    const ktt::KernelId refKernel = tuner.CreateSimpleKernel("Reference", refDef);
    tuner.SetArguments(refDef, in.boundary);

    // ===================== BEGIN CACAO:KERNELS (LLM) ========================
    const ktt::KernelDefinitionId def = tuner.AddKernelDefinitionFromFile(
        "gemm_fast", kernelFile, ndRange, ktt::DimensionVector());
    ktt::KernelId kernel = tuner.CreateSimpleKernel("Gemm", def);
    tuner.SetArguments(def, {in.kSizeM_, in.kSizeN_, in.kSizeK_, in.mat_a, in.mat_b, in.mat_c});
    // ===================== END CACAO:KERNELS ================================

    // ===================== BEGIN CACAO:PARAMS (LLM) =========================
    tuner.AddParameter(kernel, "MWG",   std::vector<uint64_t>{16, 32, 64});
    tuner.AddParameter(kernel, "NWG",   std::vector<uint64_t>{16, 32, 64});
    tuner.AddParameter(kernel, "KWG",   std::vector<uint64_t>{32});
    tuner.AddParameter(kernel, "MDIMC", std::vector<uint64_t>{8, 16, 32});
    tuner.AddParameter(kernel, "NDIMC", std::vector<uint64_t>{8, 16, 32});
    tuner.AddParameter(kernel, "MDIMA", std::vector<uint64_t>{8, 16, 32});
    tuner.AddParameter(kernel, "NDIMB", std::vector<uint64_t>{8, 16, 32});
    tuner.AddParameter(kernel, "KWI",   std::vector<uint64_t>{2});
    tuner.AddParameter(kernel, "VWM",   std::vector<uint64_t>{1, 2, 4});
    tuner.AddParameter(kernel, "VWN",   std::vector<uint64_t>{1, 2, 4});
    tuner.AddParameter(kernel, "STRM",  std::vector<uint64_t>{0});
    tuner.AddParameter(kernel, "STRN",  std::vector<uint64_t>{0});
    tuner.AddParameter(kernel, "SA",    std::vector<uint64_t>{0, 1});
    tuner.AddParameter(kernel, "SB",    std::vector<uint64_t>{0, 1});
    tuner.AddParameter(kernel, "PRECISION", std::vector<uint64_t>{32});

    auto globalMod = [](const uint64_t size, const std::vector<uint64_t>& v) { return size * v.at(0) / v.at(1); };
    tuner.AddThreadModifier(kernel, {def}, ktt::ModifierType::Global, ktt::ModifierDimension::X, {"MDIMC", "MWG"}, globalMod);
    tuner.AddThreadModifier(kernel, {def}, ktt::ModifierType::Global, ktt::ModifierDimension::Y, {"NDIMC", "NWG"}, globalMod);
    tuner.AddThreadModifier(kernel, {def}, ktt::ModifierType::Local,  ktt::ModifierDimension::X, "MDIMC", ktt::ModifierAction::Multiply);
    tuner.AddThreadModifier(kernel, {def}, ktt::ModifierType::Local,  ktt::ModifierDimension::Y, "NDIMC", ktt::ModifierAction::Multiply);

    auto isMultiple    = [](const uint64_t a, const uint64_t b) { return (a / b) * b == a; };
    auto multipleOfXY  = [&](const std::vector<uint64_t>& v) { return isMultiple(v[0], v[1] * v[2]); };
    auto multipleOfXYZ = [&](const std::vector<uint64_t>& v) { return isMultiple(v[0], (v[1] * v[2]) / v[3]); };
    tuner.AddConstraint(kernel, {"KWG", "KWI"}, [&](const std::vector<uint64_t>& v) { return isMultiple(v[0], v[1]); });
    tuner.AddConstraint(kernel, {"MWG", "MDIMC", "VWM"}, multipleOfXY);
    tuner.AddConstraint(kernel, {"NWG", "NDIMC", "VWN"}, multipleOfXY);
    tuner.AddConstraint(kernel, {"MWG", "MDIMA", "VWM"}, multipleOfXY);
    tuner.AddConstraint(kernel, {"NWG", "NDIMB", "VWN"}, multipleOfXY);
    tuner.AddConstraint(kernel, {"KWG", "MDIMC", "NDIMC", "MDIMA"}, multipleOfXYZ);
    tuner.AddConstraint(kernel, {"KWG", "MDIMC", "NDIMC", "NDIMB"}, multipleOfXYZ);
    // ===================== END CACAO:PARAMS =================================

    // ===================== BEGIN CACAO:LAUNCHER (LLM) =======================
    // LAUNCHER region (LLM): single kernel uses default launch
    // ===================== END CACAO:LAUNCHER ===============================

    // ---- validation + search + run (engine-owned) ----
    tuner.SetValidationMethod(ktt::ValidationMethod::SideBySideComparison, tolerance);
    tuner.SetReferenceKernel(in.validated, refKernel, ktt::KernelConfiguration());
    tuner.SetSearcher(kernel, std::make_unique<ktt::RandomSearcher>());
    const auto results = tuner.Tune(kernel, std::make_unique<ktt::TuningDuration>(duration));
    tuner.SaveResults(results, output, ktt::OutputFormat::JSON);

    std::cout << "Tuning done: " << results.size() << " configurations -> " << output << "\n";
    return 0;
}
