// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int M = 2048;
inline constexpr int N = 2048;
inline constexpr int K = 2048;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<float> gen_mat_a() {
    std::vector<float> v(static_cast<size_t>(M) * static_cast<size_t>(K));
    std::mt19937 rng(1886651486u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_mat_b() {
    std::vector<float> v(static_cast<size_t>(N) * static_cast<size_t>(K));
    std::mt19937 rng(3917305316u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_mat_c() {
    return std::vector<float>(static_cast<size_t>(M) * static_cast<size_t>(N), 0.0f);
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId mat_a;
    ktt::ArgumentId mat_b;
    ktt::ArgumentId mat_c;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.mat_a = t.AddArgumentVector(gen_mat_a(), ktt::ArgumentAccessType::ReadOnly);
    in.mat_b = t.AddArgumentVector(gen_mat_b(), ktt::ArgumentAccessType::ReadOnly);
    in.mat_c = t.AddArgumentVector(gen_mat_c(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.mat_c};
    in.boundary  = {in.mat_a, in.mat_b, in.mat_c};
    in.defines   = " -DM=2048 -DN=2048 -DK=2048";
    return in;
}
