"""Framework-file codegen.

Assembles a per-iteration ``framework.cpp`` KTT driver from:
  * ``problem.yaml`` metadata (global-size type, base grid, reference), and
  * the three LLM-authored region bodies (KERNELS / PARAMS / LAUNCHER).

The driver is *argument-agnostic*: the entire I/O boundary (scalars, buffers,
which one is validated, arg order) lives in the user-owned ``inputs.hpp`` and is
consumed at runtime via the ``Inputs`` struct returned by ``DefineInputs()``.
Only compile-time/structural values are baked in here; runtime scalars
(duration, tolerance, indices, paths) are passed as argv.

See docs/FRAMEWORK_FILE_SPEC.md.
"""
from __future__ import annotations

import argparse
import textwrap
from pathlib import Path

import yaml

DEFAULT_CUDA_INCLUDE = "/usr/local/cuda/include"

_TEMPLATE = """\
// framework.cpp — GENERATED by utils/framework.py. Do not edit by hand.
// Engine skeleton (argument-agnostic) + user inputs.hpp + three LLM regions.
#include <iostream>
#include <memory>
#include <string>
#include <vector>

#include <Ktt.h>
#include "inputs.hpp"

int main(int argc, char** argv)
{{
    // ---- runtime args (argv) ----
    ktt::PlatformIndex platform = (argc > 1) ? std::stoul(argv[1]) : 0;
    ktt::DeviceIndex   device   = (argc > 2) ? std::stoul(argv[2]) : 0;
    const double       duration  = (argc > 3) ? std::stod(argv[3]) : {duration};
    const double       tolerance = (argc > 4) ? std::stod(argv[4]) : {tolerance};
    const std::string  output     = (argc > 5) ? argv[5] : "results";
    const std::string  kernelFile = (argc > 6) ? argv[6] : "kernels.cu";
    const std::string  refFile    = (argc > 7) ? argv[7] : "{ref_file}";

    // ---- tuner ----
    ktt::Tuner tuner(platform, device, ktt::ComputeApi::CUDA);
    tuner.SetGlobalSizeType(ktt::GlobalSizeType::{gst});
    tuner.SetTimeUnit(ktt::TimeUnit::Microseconds);
    tuner.SetCompilerOptions("-I{cuda_include}");

    const ktt::DimensionVector ndRange({ndrange});

    // ---- inputs (user-owned; the entire I/O boundary) ----
    Inputs in = DefineInputs(tuner);

    // ---- reference kernel (engine-owned validation) ----
    const ktt::KernelDefinitionId refDef = tuner.AddKernelDefinitionFromFile(
        "{ref_func}", refFile, ndRange, ktt::DimensionVector({ref_block}));
    const ktt::KernelId refKernel = tuner.CreateSimpleKernel("Reference", refDef);
    tuner.SetArguments(refDef, in.boundary);

    // ===================== BEGIN CACAO:KERNELS (LLM) ========================
{kernels}
    // ===================== END CACAO:KERNELS ================================

    // ===================== BEGIN CACAO:PARAMS (LLM) =========================
{params}
    // ===================== END CACAO:PARAMS =================================

    // ===================== BEGIN CACAO:LAUNCHER (LLM) =======================
{launcher}
    // ===================== END CACAO:LAUNCHER ===============================

    // ---- validation + search + run (engine-owned) ----
    tuner.SetValidationMethod(ktt::ValidationMethod::SideBySideComparison, tolerance);
    tuner.SetReferenceKernel(in.validated, refKernel, ktt::KernelConfiguration());
    tuner.SetSearcher(kernel, std::make_unique<ktt::RandomSearcher>());
    const auto results = tuner.Tune(kernel, std::make_unique<ktt::TuningDuration>(duration));
    tuner.SaveResults(results, output, ktt::OutputFormat::JSON);

    std::cout << "Tuning done: " << results.size() << " configurations -> " << output << "\\n";
    return 0;
}}
"""


def _dim_args(d: dict) -> str:
    """Build DimensionVector ctor args from an {x,y,z} mapping (x required)."""
    parts = [str(d["x"])]
    if "y" in d:
        parts.append(str(d["y"]))
    if "z" in d:
        parts.append(str(d["z"]))
    return ", ".join(parts)


def _region(body: str, empty_hint: str) -> str:
    """Indent an LLM region body into the driver, or emit a placeholder comment."""
    body = (body or "").strip("\n")
    if not body.strip():
        return textwrap.indent(f"// {empty_hint}", "    ")
    return textwrap.indent(body, "    ")


def assemble_framework_cpp(
    meta: dict,
    regions: dict,
    cuda_include: str = DEFAULT_CUDA_INCLUDE,
) -> str:
    """Assemble framework.cpp from problem metadata + the three region bodies."""
    gst = "OpenCL" if str(meta.get("global_size_type", "cuda")).lower() == "opencl" else "CUDA"
    ref = meta["reference"]
    return _TEMPLATE.format(
        duration=float((meta.get("tuning") or {}).get("duration_s", 20.0)),
        tolerance=float((meta.get("validation") or {}).get("tolerance", 1e-4)),
        ref_file=ref["file"],
        gst=gst,
        cuda_include=cuda_include,
        ndrange=_dim_args(meta["grid"]),
        ref_func=ref["function"],
        ref_block=_dim_args(ref.get("block", {"x": 1})),
        kernels=_region(regions.get("kernels", ""), "KERNELS region (LLM): define defs, `kernel`, SetArguments"),
        params=_region(regions.get("params", ""), "PARAMS region (LLM): AddParameter / AddConstraint / AddThreadModifier"),
        launcher=_region(regions.get("launcher", ""), "LAUNCHER region (LLM): single kernel uses default launch"),
    )


def main() -> int:
    p = argparse.ArgumentParser(description="Assemble framework.cpp from problem.yaml + LLM regions")
    p.add_argument("--problem", required=True, help="path to framework-mode problem.yaml")
    p.add_argument("--kernels", help="file with the CACAO:KERNELS region body")
    p.add_argument("--params", help="file with the CACAO:PARAMS region body")
    p.add_argument("--launcher", help="file with the CACAO:LAUNCHER region body")
    p.add_argument("--out", required=True, help="output framework.cpp path")
    p.add_argument("--cuda-include", default=DEFAULT_CUDA_INCLUDE)
    args = p.parse_args()

    meta = yaml.safe_load(Path(args.problem).read_text())
    regions = {
        "kernels": Path(args.kernels).read_text() if args.kernels else "",
        "params": Path(args.params).read_text() if args.params else "",
        "launcher": Path(args.launcher).read_text() if args.launcher else "",
    }
    Path(args.out).write_text(assemble_framework_cpp(meta, regions, args.cuda_include))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
