"""Generate a problem's inputs.hpp from its structured spec (models/inputs.py).

Mirrors utils/framework.py: structured data -> C++ text, no templating engine. The
spec in inputs.yaml is canonical and inputs.hpp is always regenerated from it, so the
create/edit form never has to parse C++ back into form state.

Target: reproduce problems/mmul/inputs.hpp, a file proven to compile, tune, and
validate 106/106 on the GPU.
"""

from __future__ import annotations

import re
import textwrap
import zlib
from pathlib import Path

import yaml

from models.inputs import BufferSpec, InputsSpec, ScalarSpec

_ACCESS = {
    "read": "ReadOnly",
    "write": "WriteOnly",
    "readwrite": "ReadWrite",
}


def _seed(name: str) -> int:
    """Deterministic per-buffer RNG seed.

    crc32, not hash(): Python's hash() is salted per process, which would make a
    problem's input data differ between runs and break reproducibility of timings.
    """
    return zlib.crc32(name.encode()) & 0xFFFFFFFF


def _literal(value, dtype: str) -> str:
    """C++ literal for a spec value. Floats need the f suffix to stay single-precision."""
    if dtype == "float":
        return f"{float(value)}f"
    return str(int(value))


def _scalar_ids(spec: InputsSpec) -> dict:
    """ArgumentId member name per runtime scalar.

    Trailing underscore so the id reads distinctly from the host constexpr of the same
    name (`in.kSizeM_` vs `kSizeM`), matching problems/mmul/inputs.hpp.
    """
    return {s.name: f"{s.name}_" for s in spec.scalars if "runtime" in s.placements}


def _member(arg, scalar_ids: dict) -> str:
    return scalar_ids[arg.name] if arg.kind == "scalar" else arg.name


def _size_expr(spec: InputsSpec, expr: str) -> str:
    """Widen every scalar in a size expression to size_t.

    Casting the whole expression -- static_cast<size_t>(kSizeM * kSizeK) -- widens only
    the RESULT: the multiply still happens in int and can overflow first. Widening each
    operand instead makes the arithmetic itself 64-bit.
    """
    names = sorted((s.name for s in spec.scalars if "host" in s.placements), key=len, reverse=True)
    for name in names:
        expr = re.sub(rf"\b{re.escape(name)}\b", f"static_cast<size_t>({name})", expr)
    return expr


def _generator(spec: InputsSpec, buf: BufferSpec) -> str:
    ctype = buf.dtype
    size = _size_expr(spec, buf.size)

    if buf.init == "custom":
        body = textwrap.indent(textwrap.dedent(buf.body).strip(), "    ")
        return f"inline std::vector<{ctype}> gen_{buf.name}() {{\n{body}\n}}"

    if buf.init == "zeros":
        zero = _literal(0, ctype)
        return (
            f"inline std::vector<{ctype}> gen_{buf.name}() {{\n"
            f"    return std::vector<{ctype}>({size}, {zero});\n"
            f"}}"
        )

    lo = _literal(buf.min if buf.min is not None else (-1 if ctype == "float" else 0), ctype)
    hi = _literal(buf.max if buf.max is not None else 1, ctype)
    dist = "uniform_real_distribution" if ctype == "float" else "uniform_int_distribution"
    return (
        f"inline std::vector<{ctype}> gen_{buf.name}() {{\n"
        f"    std::vector<{ctype}> v({size});\n"
        f"    std::mt19937 rng({_seed(buf.name)}u);\n"
        f"    std::{dist}<{ctype}> d({lo}, {hi});\n"
        f"    for (auto& x : v) x = d(rng);\n"
        f"    return v;\n"
        f"}}"
    )


def _defines(spec: InputsSpec) -> str:
    """-D macros for `define`-placement scalars, as one compiler-options fragment.

    Emitted into Inputs.defines rather than passed to SetCompilerOptions from here:
    KTT's SetCompilerOptions REPLACES the option string (Tuner.h:908) and the engine
    skeleton already calls it with the CUDA include path, so a call from inside
    DefineInputs would wipe that include and break every NVRTC compile. The skeleton
    concatenates this string instead.
    """
    parts = [
        f"-D{s.name}={_literal(s.value, s.dtype)}"
        for s in spec.scalars
        if "define" in s.placements
    ]
    return " ".join(parts)


def generate_inputs_hpp(spec: InputsSpec) -> str:
    """Render the spec as the inputs.hpp the engine compiles."""
    scalar_ids = _scalar_ids(spec)

    out: list[str] = [
        "// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.",
        "// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument",
        "// registration, and which buffer is validated. The engine skeleton is",
        "// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().",
        "#pragma once",
        "#include <string>",
        "#include <vector>",
        "#include <random>",
        "#include <Ktt.h>",
    ]
    out += [f"#include {h}" for h in spec.headers]

    host = [s for s in spec.scalars if "host" in s.placements]
    if host:
        out.append("")
        out.append("// --- scalars (host consts) ---------------------------------------------------")
        out += [
            f"inline constexpr {s.dtype} {s.name} = {_literal(s.value, s.dtype)};"
            for s in host
        ]

    if spec.shared_setup.strip():
        out.append("")
        out.append("// --- shared setup (coupled/derived data) -------------------------------------")
        out.append(textwrap.dedent(spec.shared_setup).strip())

    if spec.buffers:
        out.append("")
        out.append("// --- data generators (one per buffer) ----------------------------------------")
        out += [_generator(spec, b) for b in spec.buffers]

    # --- Inputs struct ---
    out.append("")
    out.append("// --- boundary exposed to the engine skeleton + the LLM regions ---------------")
    out.append("struct Inputs {")
    for arg in spec.args:
        if arg.kind == "scalar" and arg.name not in scalar_ids:
            continue  # host-const / define-only: no ArgumentId exists
        out.append(f"    ktt::ArgumentId {_member(arg, scalar_ids)};")
    out.append("    ktt::ArgumentId validated;              // buffer checked against the reference")
    out.append("    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order")
    out.append("    std::string defines;                    // -D macros; the skeleton appends these")
    out.append("};")

    # --- DefineInputs ---
    out.append("")
    out.append("inline Inputs DefineInputs(ktt::Tuner& t) {")
    out.append("    Inputs in;")
    for arg in spec.args:
        if arg.kind == "scalar":
            if arg.name in scalar_ids:
                out.append(f"    in.{scalar_ids[arg.name]} = t.AddArgumentScalar({arg.name});")
        else:
            out.append(
                f"    in.{arg.name} = t.AddArgumentVector(gen_{arg.name}(), "
                f"ktt::ArgumentAccessType::{_ACCESS[arg.access]});"
            )
    out.append(f"    in.validated = in.{spec.validated.name};")
    boundary = ", ".join(f"in.{_member(a, scalar_ids)}" for a in spec.boundary)
    out.append(f"    in.boundary  = {{{boundary}}};")
    out.append(f'    in.defines   = "{_defines(spec)}";')
    out.append("    return in;")
    out.append("}")

    return "\n".join(out) + "\n"


def load_inputs_spec(path: Path) -> InputsSpec:
    return InputsSpec.model_validate(yaml.safe_load(Path(path).read_text()) or {})


def write_inputs(problem_dir: Path, spec: InputsSpec) -> None:
    """Persist the canonical spec and the generated header side by side."""
    problem_dir = Path(problem_dir)
    problem_dir.joinpath("inputs.yaml").write_text(
        yaml.safe_dump(spec.model_dump(by_alias=True, exclude_none=True), sort_keys=False)
    )
    problem_dir.joinpath("inputs.hpp").write_text(generate_inputs_hpp(spec))
