// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>
#include <cstring>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int CLIENTS = 8192;
inline constexpr int PERIODS = 8192;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<int> gen_changes() {
    std::vector<int> v(static_cast<size_t>(CLIENTS) * static_cast<size_t>(PERIODS));
    std::mt19937 rng(539015229u);
    std::uniform_int_distribution<int> d(-2, 2);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<int> gen_account() {
    return std::vector<int>(static_cast<size_t>(CLIENTS) * static_cast<size_t>(PERIODS), 0);
}
inline std::vector<int> gen_sum() {
    return std::vector<int>(static_cast<size_t>(PERIODS), 0);
}

// --- CPU reference (ref_cpu.c, linked into the driver; scalars are -D flags) --
extern "C" void savings_reference(const int* changes, int* account, int* sum);
namespace cacao_ref {
inline const std::vector<int> h_changes = gen_changes();
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId changes;
    ktt::ArgumentId account;
    ktt::ArgumentId sum;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.changes = t.AddArgumentVector(cacao_ref::h_changes, ktt::ArgumentAccessType::ReadOnly);
    in.account = t.AddArgumentVector(gen_account(), ktt::ArgumentAccessType::WriteOnly);
    in.sum = t.AddArgumentVector(gen_sum(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.account, in.sum};
    in.boundary  = {in.changes, in.account, in.sum};
    in.defines   = " -DCLIENTS=8192 -DPERIODS=8192";

    // CPU reference: one computation per validated buffer (engine skeleton
    // skips SetReferenceKernel when the problem's reference is cpu_c).
    t.SetReferenceComputation(in.account, [](void* buffer) {
        std::vector<int> s_sum(static_cast<size_t>(PERIODS));
        savings_reference(cacao_ref::h_changes.data(), static_cast<int*>(buffer), s_sum.data());
    });
    t.SetReferenceComputation(in.sum, [](void* buffer) {
        std::vector<int> s_account(static_cast<size_t>(CLIENTS) * static_cast<size_t>(PERIODS));
        savings_reference(cacao_ref::h_changes.data(), s_account.data(), static_cast<int*>(buffer));
    });
    return in;
}
