// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>
#include <cstring>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int COV_M = 8192;
inline constexpr int COV_K = 512;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<float> gen_data() {
    std::vector<float> v(static_cast<size_t>(COV_M) * static_cast<size_t>(COV_K));
    std::mt19937 rng(2918445923u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_cov() {
    return std::vector<float>(static_cast<size_t>(COV_K) * static_cast<size_t>(COV_K), 0.0f);
}

// --- CPU reference (ref_cpu.c, linked into the driver; scalars are -D flags) --
extern "C" void covariance_reference(const float* data, float* cov);
namespace cacao_ref {
inline const std::vector<float> h_data = gen_data();
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId data;
    ktt::ArgumentId cov;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.data = t.AddArgumentVector(cacao_ref::h_data, ktt::ArgumentAccessType::ReadOnly);
    in.cov = t.AddArgumentVector(gen_cov(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.cov};
    in.boundary  = {in.data, in.cov};
    in.defines   = " -DCOV_M=8192 -DCOV_K=512";

    // CPU reference: one computation per validated buffer (engine skeleton
    // skips SetReferenceKernel when the problem's reference is cpu_c).
    t.SetReferenceComputation(in.cov, [](void* buffer) {
        covariance_reference(cacao_ref::h_data.data(), static_cast<float*>(buffer));
    });
    return in;
}
