// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>
#include <cstring>
#include <cmath>
#include <algorithm>
#include <numeric>
#include <cstdint>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int MAP_W = 2048;
inline constexpr int MAP_H = 2048;
inline constexpr int LEVEL = 600;
inline constexpr int SRC_X = 0;
inline constexpr int SRC_Y = 0;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<int> gen_heights() {
    // Seeded multi-octave value-noise fBm, then rank-transformed to a uniform 0..999.
    // The rank transform is monotonic, so it preserves the level-set topology exactly:
    // the flood region at percentile p is identical to the raw fBm's. It buys exact
    // control over how much terrain is floodable at a given LEVEL, for free.
    const size_t n = static_cast<size_t>(MAP_W) * static_cast<size_t>(MAP_H);
    std::vector<float> h(n);

    auto hash2 = [](int x, int y) -> float {
        uint32_t s = uint32_t(x) * 374761393u + uint32_t(y) * 668265263u;
        s = (s ^ (s >> 13)) * 1274126177u;
        return float((s ^ (s >> 16)) & 0xFFFFFFu) / float(0xFFFFFFu);
    };
    auto lerp = [](float a, float b, float t) { return a + (b - a) * t; };
    auto vnoise = [&](float x, float y) {
        int xi = int(std::floor(x)), yi = int(std::floor(y));
        float xf = x - float(xi), yf = y - float(yi);
        float u = xf * xf * (3.0f - 2.0f * xf);
        float v = yf * yf * (3.0f - 2.0f * yf);
        return lerp(lerp(hash2(xi, yi),     hash2(xi + 1, yi),     u),
                    lerp(hash2(xi, yi + 1), hash2(xi + 1, yi + 1), u), v);
    };

    for (int y = 0; y < MAP_H; ++y) {
        for (int x = 0; x < MAP_W; ++x) {
            float f = 0.0f, amp = 1.0f, frq = 1.0f / 128.0f, norm = 0.0f;
            for (int o = 0; o < 6; ++o) {
                f += amp * vnoise(float(x) * frq, float(y) * frq);
                norm += amp; amp *= 0.5f; frq *= 2.0f;
            }
            h[static_cast<size_t>(y) * MAP_W + x] = f / norm;
        }
    }

    std::vector<uint32_t> idx(n);
    std::iota(idx.begin(), idx.end(), 0u);
    std::sort(idx.begin(), idx.end(),
              [&](uint32_t a, uint32_t b) { return h[a] < h[b]; });

    std::vector<int> out(n);
    for (size_t r = 0; r < n; ++r) out[idx[r]] = int(r * 1000 / n);
    out[static_cast<size_t>(SRC_Y) * MAP_W + SRC_X] = 0;  // source is always floodable
    return out;
}
inline std::vector<int> gen_flooded() {
    return std::vector<int>(static_cast<size_t>(MAP_W) * static_cast<size_t>(MAP_H), 0);
}

// --- CPU reference (ref_cpu.c, linked into the driver; scalars are -D flags) --
extern "C" void flood_reference(const int* heights, int* flooded);
namespace cacao_ref {
inline const std::vector<int> h_heights = gen_heights();
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId heights;
    ktt::ArgumentId flooded;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.heights = t.AddArgumentVector(cacao_ref::h_heights, ktt::ArgumentAccessType::ReadOnly);
    in.flooded = t.AddArgumentVector(gen_flooded(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.flooded};
    in.boundary  = {in.heights, in.flooded};
    in.defines   = " -DMAP_W=2048 -DMAP_H=2048 -DLEVEL=600 -DSRC_X=0 -DSRC_Y=0";

    // CPU reference: one computation per validated buffer (engine skeleton
    // skips SetReferenceKernel when the problem's reference is cpu_c).
    t.SetReferenceComputation(in.flooded, [](void* buffer) {
        flood_reference(cacao_ref::h_heights.data(), static_cast<int*>(buffer));
    });
    return in;
}
