// inputs.hpp — GENERATED by utils/inputs.py from inputs.yaml. Do not edit by hand.
// Owns the problem's ENTIRE I/O boundary: scalars, data generators, KTT argument
// registration, and which buffers are validated. The engine skeleton is
// argument-agnostic and consumes only the Inputs struct returned by DefineInputs().
#pragma once
#include <string>
#include <vector>
#include <random>
#include <Ktt.h>
#include <cstring>

// --- scalars (host consts) ---------------------------------------------------
inline constexpr int N = 50000;

// --- data generators (one per buffer) ----------------------------------------
inline std::vector<float> gen_Ax() {
    std::vector<float> v(static_cast<size_t>(N));
    std::mt19937 rng(4133852597u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_Ay() {
    std::vector<float> v(static_cast<size_t>(N));
    std::mt19937 rng(2170725667u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_Az() {
    std::vector<float> v(static_cast<size_t>(N));
    std::mt19937 rng(409728153u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_Bx() {
    std::vector<float> v(static_cast<size_t>(N));
    std::mt19937 rng(3712534134u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_By() {
    std::vector<float> v(static_cast<size_t>(N));
    std::mt19937 rng(2857367264u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_Bz() {
    std::vector<float> v(static_cast<size_t>(N));
    std::mt19937 rng(860268378u);
    std::uniform_real_distribution<float> d(-2.0f, 2.0f);
    for (auto& x : v) x = d(rng);
    return v;
}
inline std::vector<float> gen_result() {
    return std::vector<float>(1, 0.0f);
}

// --- CPU reference (ref_cpu.c, linked into the driver; scalars are -D flags) --
extern "C" void galaxies_reference(const float* Ax, const float* Ay, const float* Az, const float* Bx, const float* By, const float* Bz, float* result);
namespace cacao_ref {
inline const std::vector<float> h_Ax = gen_Ax();
inline const std::vector<float> h_Ay = gen_Ay();
inline const std::vector<float> h_Az = gen_Az();
inline const std::vector<float> h_Bx = gen_Bx();
inline const std::vector<float> h_By = gen_By();
inline const std::vector<float> h_Bz = gen_Bz();
}

// --- boundary exposed to the engine skeleton + the LLM regions ---------------
struct Inputs {
    ktt::ArgumentId Ax;
    ktt::ArgumentId Ay;
    ktt::ArgumentId Az;
    ktt::ArgumentId Bx;
    ktt::ArgumentId By;
    ktt::ArgumentId Bz;
    ktt::ArgumentId result;
    std::vector<ktt::ArgumentId> validated; // buffers checked against the reference
    std::vector<ktt::ArgumentId> boundary;  // args in reference-signature order
    std::string defines;                    // -D macros; the skeleton appends these
};

inline Inputs DefineInputs(ktt::Tuner& t) {
    Inputs in;
    in.Ax = t.AddArgumentVector(cacao_ref::h_Ax, ktt::ArgumentAccessType::ReadOnly);
    in.Ay = t.AddArgumentVector(cacao_ref::h_Ay, ktt::ArgumentAccessType::ReadOnly);
    in.Az = t.AddArgumentVector(cacao_ref::h_Az, ktt::ArgumentAccessType::ReadOnly);
    in.Bx = t.AddArgumentVector(cacao_ref::h_Bx, ktt::ArgumentAccessType::ReadOnly);
    in.By = t.AddArgumentVector(cacao_ref::h_By, ktt::ArgumentAccessType::ReadOnly);
    in.Bz = t.AddArgumentVector(cacao_ref::h_Bz, ktt::ArgumentAccessType::ReadOnly);
    in.result = t.AddArgumentVector(gen_result(), ktt::ArgumentAccessType::WriteOnly);
    in.validated = {in.result};
    in.boundary  = {in.Ax, in.Ay, in.Az, in.Bx, in.By, in.Bz, in.result};
    in.defines   = " -DN=50000";

    // CPU reference: one computation per validated buffer (engine skeleton
    // skips SetReferenceKernel when the problem's reference is cpu_c).
    t.SetReferenceComputation(in.result, [](void* buffer) {
        galaxies_reference(cacao_ref::h_Ax.data(), cacao_ref::h_Ay.data(), cacao_ref::h_Az.data(), cacao_ref::h_Bx.data(), cacao_ref::h_By.data(), cacao_ref::h_Bz.data(), static_cast<float*>(buffer));
    });
    return in;
}
